"""empty message

Revision ID: 42a2ec9966e2
Revises: c1763ce50bbc
Create Date: 2021-01-26 20:09:40.247696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a2ec9966e2'
down_revision = 'c1763ce50bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', sa.String(length=600), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###
