"""empty message

Revision ID: 929c7a6f9d17
Revises: 63303f8b8025
Create Date: 2021-01-24 18:38:53.266084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929c7a6f9d17'
down_revision = '63303f8b8025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
