"""empty message

Revision ID: d18e93acbbc0
Revises: 42a2ec9966e2
Create Date: 2021-01-26 20:27:27.275514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd18e93acbbc0'
down_revision = '42a2ec9966e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=600), nullable=True))
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', mysql.VARCHAR(collation='utf8_unicode_ci', length=600), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
